# Configuration globale pour le pipeline de Détection d'Anomalies PolSAR
# Approche Deep Learning (Unet Complexe)

seed: 42
task: "segmentation"

# --- 1. Architecture du Modèle ---
model:
  class: UNet
  num_layers: 3
  channels_width: 16
  activation: "CReLU" 
  num_blocks: 3
  layer_mode: "complex"
  normalization_layer: "batch"
  downsampling_layer: "maxpool"
  upsampling_layer: "nearest"
  residual: True
  projection_layer: "amplitude"
  projection_config: None
  dropout: 0.0
  gumbel_softmax: None
  

# --- 2. Configuration des Données ---
data:
  dataset:
    name: PolSFDataset
    trainpath: "./data/SAN_FRANCISCO_ALOS2"
    base_dir: "/home/nicolas/Documents/polSAR_Control/data"
    patch_size: 64
    patch_stride: 16
  batch_size: 32
  num_workers: 2
  valid_ratio: 0.1
  test_ratio: 0.1
  shuffle: True

# --- 3. Type de loss ---
loss:
  name: "FocalLoss"
  use_class_weights: true
  weight_mode: "balanced"
  gamma: 2.0
  ignore_index : 0    



# --- 4. Nombre d'epochs ---
epochs: 150

# --- 5. Optimisation et Scheduler ---

# Optimizer configuration
optim:
  algo: AdamW
  params:
    lr: 0.0005 # Reduced from 0.0005 for more stable training
    weight_decay: 0.001 # Increased weight decay for better regularization
    betas: [0.9, 0.999]

# Scheduler configuration with ReduceLROnPlateau for adaptive learning
scheduler:
  name: ReduceLROnPlateau
  params:
    mode: min
    factor: 0.5
    patience: 5
    min_lr: 0.000001



# --- Suivi des Expériences avec Wandb ---
logging:
  wandb:
    project: "polSAR-anomaly-detection-DL"
