# Configuration globale pour le pipeline de Détection d'Anomalies PolSAR
# Approche Deep Learning (Auto-encodeur Complexe)

seed: 42
task: "reconstruction"

# --- 1. Architecture du Modèle ---
model:
  name: "ComplexAutoencoder"
  layer_mode: "complex"
  in_channels: 4
  num_layers: 3
  channels_width: 32             # Doit être un entier (largeur de la première couche, doublée ensuite)
  activation: "CReLU"            # CReLU (Complex ReLU) natif de cvnn
  upsampling_layer: "bilinear"
  normalization_layer: "batch"
  residual: true
  num_blocks: 1
  latent_dim: 2048
  
  # Paramètres requis pour basculer sur un VAE (setup_loss_optimizer)
  decoder_variance:
    learned_variance: false
    min_log_sigma: -20.0

# --- 2. Configuration des Données ---
data:
  dataset:
    name: "PolSFDataset"         # Ou "ALOS" selon l'intégration dans cvnn
    trainpath: "./data/SAN_FRANCISCO_ALOS2"
    base_dir: "/home/nicolas/Documents/polSAR_Control/data"
    azimut_split_x1: 1750
    azimut_split_x2: 3000
    has_labels: False
    
    patch_size: 16
    patch_stride: 16

    # Les clés importantes pour cette étape :
    type: "polsar" # Indispensable pour entrer dans la boucle H-Alpha et Cameron
    supports_full_image_reconstruction: true # La clé qui active la reconstruction

  batch_size: 32
  num_workers: 0
  shuffle: True

  # Division des données
  valid_ratio: 0.1
  test_ratio: 0.1 

  recompute_statistics: True
  
  # Pipeline de Prétraitement Modulaire
  transforms:
    #train puis valid 
   
    - name: "logamplitude"

# --- Paramètres d'entraînement Deep Learning ---
training:
  epochs: 2
  best_model_name: "best_autoencoder.pth"

loss:
  name: "MSE"               
  use_class_weights: false

# --- Optimisation et Scheduler ---
optim:
  algo: "AdamW"
  params:
    lr: 0.0005
    weight_decay: 0.0001

scheduler:
  name: "ReduceLROnPlateau"
  params:
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: 0.00001

# --- Suivi des Expériences ---
logging:
  wandb:
    project: "polSAR-anomaly-detection-DL"
